import type { Metadata } from 'next'

import { GEIST_MONO, GEIST_SANS } from '@/lib/font'
import { cn } from '@/lib/utils'

import { TailwindIndicator } from '@/components/common'
import { RThemeProvider } from '@/components/provider'
import { Toaster } from '@/components/ui/sonner'

import './globals.css'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={cn(GEIST_SANS.variable, GEIST_MONO.variable)}>
                <RThemeProvider>
                    <TailwindIndicator />
                    <Toaster />
                    {children}
                </RThemeProvider>
            </body>
        </html>
    )
}
